[[tests]]
name = "get_bitseq"
input = ["./$project", "get_bitseq", "94116", "12", "15"]
expected = """
C: 6
Asm: 6
Emu: 6
"""
rubric = 6

[[tests]]
name = "fib_rec"
input = ["./$project", "fib_rec", "10"]
expected = """
C: 55
Asm: 55
Emu: 55
"""
rubric = 6

[[tests]]
name = "is_pal"
input = ["./$project", "is_pal", "941171149"]
expected = """
C: is a palindrome
Asm: is a palindrome
Emu: is a palindrome
"""
rubric = 6

[[tests]]
name = "max3"
input = ["./$project", "max3", "2", "10", "8"]
expected = """
C: 10
Asm: 10
Emu: 10
"""
rubric = 6

[[tests]]
name = "merge_sort"
input = ["./$project", "merge_sort", "6", "4", "1", "2", "5", "3"]
expected = """
C: 1 2 3 4 5 6
Asm: 1 2 3 4 5 6
Emu: 1 2 3 4 5 6
"""
rubric = 15

[[tests]]
name = "midpoint"
input = ["./$project", "midpoint", "0", "4"]
expected = """
C: 2
Asm: 2
Emu: 2
"""
rubric = 14

[[tests]]
name = "quadratic"
input = ["./$project", "quadratic", "2", "4", "6", "8"]
expected = """
C: 36
Asm: 36
Emu: 36
"""
rubric = 6

[[tests]]
name = "sort"
input = ["./$project", "sort", "6", "4", "1", "2", "5", "3"]
expected = """
C: 6 5 4 3 2 1
Asm: 6 5 4 3 2 1
Emu: 6 5 4 3 2 1
"""
rubric = 15

[[tests]]
name = "to_upper"
input = ["./$project", "to_upper", "FooBar"]
expected = """
C: FOOBAR
Asm: FOOBAR
Emu: FOOBAR
"""
rubric = 6


