[project]
build = "none"
strip_output = """
Use default settings!
"""

[[tests]]
name = "dp-reg"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/dp-reg-test.dig"]
expected = """
dp-reg-test: passed
"""
rubric = 2

[[tests]]
name = "dp-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/dp-imm-test.dig"]
expected = """
dp-imm-test: passed
"""
rubric = 2

[[tests]]
name = "dp-lsl-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/dp-lsl-imm-test.dig"]
expected = """
dp-lsl-imm-test: passed
"""
rubric = 2

[[tests]]
name = "dp-lsr-reg"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/dp-lsr-reg-test.dig"]
expected = """
dp-lsr-reg-test: passed
"""
rubric = 2

[[tests]]
name = "dp-asr-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/dp-asr-imm-test.dig"]
expected = """
dp-asr-imm-test: passed
"""
rubric = 2

[[tests]]
name = "mem-reg"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/mem-reg-test.dig"]
expected = """
mem-reg-test: passed
"""
rubric = 2

[[tests]]
name = "mem-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/mem-imm-test.dig"]
expected = """
mem-imm-test: passed
"""
rubric = 2

[[tests]]
name = "mem-shift-reg"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/mem-shift-reg-test.dig"]
expected = """
mem-shift-reg-test: passed
"""
rubric = 2

[[tests]]
name = "blbx"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/blbx-test.dig"]
expected = """
blbx-test: passed
"""
rubric = 2

[[tests]]
name = "b"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/b-test.dig"]
expected = """
b-test: passed
"""
rubric = 2

[[tests]]
name = "beq"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/beq-test.dig"]
expected = """
beq-test: passed
"""
rubric = 2

[[tests]]
name = "ble"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/ble-test.dig"]
expected = """
ble-test: passed
"""
rubric = 2

[[tests]]
name = "bgt"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/bgt-test.dig"]
expected = """
bgt-test: passed
"""
rubric = 2

[[tests]]
name = "mul"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/mul-test.dig"]
expected = """
mul-test: passed
"""
rubric = 2

[[tests]]
name = "rsb"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/rsb-test.dig"]
expected = """
rsb-test: passed
"""
rubric = 2

[[tests]]
name = "quadratic"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/quadratic-test.dig"]
expected = """
quadratic-test: passed
"""
rubric = 2

[[tests]]
name = "get_bitseq"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/get-bitseq-test.dig"]
expected = """
get-bitseq-test: passed
"""
rubric = 2

[[tests]]
name = "max3"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/max3-test.dig"]
expected = """
max3-test: passed
"""
rubric = 2

[[tests]]
name = "fib-rec"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/fib-rec-test.dig"]
expected = """
fib-rec-test: passed
"""
rubric = 2


