[project]
build = "none"
strip_output = """
Use default settings!
"""

[[tests]]
name = "add-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/add-imm-test.dig"]
expected = """
add-imm-test: passed
"""
rubric = 1

[[tests]]
name = "mov-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/mov-imm-test.dig"]
expected = """
mov-imm-test: passed
"""
rubric = 1

[[tests]]
name = "sub-imm-n"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/sub-imm-n-test.dig"]
expected = """
sub-imm-n-test: passed
"""
rubric = 1

[[tests]]
name = "cumulative"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/cumulative-test.dig"]
expected = """
cumulative-test: passed
"""
rubric = 1
